Support path-like objects (`pathlib.Path` and others)
htseq/htseq pull request #24
Opened 2021-06-23 23:30 UTC by mruffalo

As per [PEP 519](https://www.python.org/dev/peps/pep-0519/), Python 3.6 includes a protocol to specify that an object is "path-like", and builtin/standard library code has been updated to handle anything with a `__fspath__` attribute (including `pathlib.Path` objects and the `DirEntry` objects returned by `os.scandir`). Most notably, the `__builtins__.open` function can now be given anything path-like, in addition to `gzip.open` as used in this package.

HTSeq currently assumes that any input to a I/O function is either a `str` or an open file handle -- adjust this by trying to call `os.fspath` to convert to `str`. If this fails, then the input is assumed to already be an open file handle.

2021-06-23 23:41 UTC, iosonofabio requested changes
Thanks for contributing. I don't use `pathlib` a whole lot myself, but I am aware of it.

This is a simple change so it should be approved quickly. Just:
1. Make sure you don't touch existing things (.gitignore, tests) unless necessary.
2. You changed a positive query ("is it a string?") into a default assumption ("we'll assume it's a path-like") which is fine but needs a little care. What happens if the code fails with a different exception than `TypeError`? And can you add a test for a `TypeError` failure (e.g. an open file handle) and one for another failure?

Thanks again!

2021-06-23 23:41 UTC, iosonofabio commented on .gitignore
> +__pycache__/
This is irrelevant for the PR, please remove.

2021-06-23 23:41 UTC, iosonofabio commented on HTSeq/utils.py
> +        try:
This changes default behaviour, therefore testing is important. ATM you only test when this works, but not when it fails by `TypeError`. You should add test cases for when this fails by `TypeError`.

Also, what happens if this fails by any other exception?

2021-06-23 23:41 UTC, iosonofabio commented on test/test_parsers.py
> +    data_file = Path(data_folder) / 'yeast_RNASeq_excerpt.sam'
Let's keep it simple: do not touch existing tests, instead add another test for pathlib.

Also, please add tests for `TypeError` failures, since your PR changes a positive check into a default `try`.

2021-06-23 23:59 UTC, mruffalo commented on test/test_parsers.py
> +    data_file = Path(data_folder) / 'yeast_RNASeq_excerpt.sam'
Thanks, changes incoming. I had added a new test but modified the wrong copy -- oops.

2021-06-24 00:04 UTC, mruffalo commented on HTSeq/utils.py
> +        try:
The code path triggered when `os.fspath` throws a `TypeError` (assuming that this is an open file handle) is covered by many other tests, including everything which passes a file handle such as https://github.com/htseq/htseq/blob/f8cc59db8dc4b409927eeda8798e92425c1ee363/test/test_parsers.py#L32

Other types of failures are propagated as before, like `IsADirectoryError`, `PermissionError`, etc.

2021-06-24 00:06 UTC, iosonofabio commented on HTSeq/utils.py
> +        try:
no, if there's another exception you don't set `lines` anymore, so the statement `self.lines = lines` below will fail because of variable not defined (`lines`). That didn't happen before.

2021-06-24 00:10 UTC, mruffalo commented on .gitignore
> +__pycache__/
Okay, I'll make a separate PR. I was running the test suite through `pytest` locally, which left a `test/__pycache__` directory that isn't `.gitignore`d.

2021-06-24 00:11 UTC, iosonofabio commented on .gitignore
> +__pycache__/
No need for a separate PR, just commit without that line and I'll squash and merge at the end anyway.

2021-06-24 00:17 UTC, iosonofabio commented
Now I merged your other PR, so you might need to rebase

2021-06-24 00:19 UTC, mruffalo commented on HTSeq/utils.py
> +        try:
If there's another exception, that exception will be (appropriately) propagated upward as before -- this will interrupt the creation of whatever new `FileOrSequence` object (or object of a subclass, in all practical usage). Whether `self.lines` is set isn't relevant, because there won't be any object created with or without that attribute.

2021-06-24 00:32 UTC, mruffalo commented on HTSeq/utils.py
> +        try:
I didn't phrase that exactly as I'd intended: if `self.lines = lines` is reached, `lines` will always be set. If there's another exception which would leave `lines` unset, this will propagate upward immediately and prevent `self.lines = lines` from being reached.

2021-06-24 00:32 UTC, mruffalo commented
Rebased, thanks very much!

2021-06-24 03:17 UTC, iosonofabio commented on HTSeq/utils.py
> +        try:
The assumption seems to be that only line 36 can throw a TypeError, in which case the result is assumed to be a file handle. I'm not super happy about that. It'd be better to have:

```python

try:
    fos = os.fspath(self.fos)
    fos_is_path = True
except TypeError:
    # assumed to be a file handle
    lines = self.fos
    fos_is_path = False

if fos_is_path:
    self.should_close = True
    if fos.lower().endswith((".gz", ".gzip")):
        lines = gzip.open(self.fos, 'rt')
    else:
        lines = open(self.fos)
```

That way it's more targeted and cleaner

2021-09-26 23:23 UTC, merged